LIBPATH := ../fmod/lib/web/libfmodbridge.a

SOURCES = \
	src/fmod_init.c \
	src/fmod_generated.c

HEADERS = src/fmod_bridge.h

CC := emcc
AR := emar

CFLAGS := -O3 -fvisibility=hidden -I./include -s ALLOW_MEMORY_GROWTH=1 -s LEGACY_RUNTIME=1
all: $(LIBPATH)

OBJECTS = $(patsubst src/%.c,build/js-%.o,$(SOURCES))

build/js-%.o: src/%.c $(HEADERS)
	$(CC) $(CFLAGS) -c $< -o $@

$(LIBPATH): $(OBJECTS)
	$(AR) rcs $@ $^

clean:
	rm -f $(LIBPATH) build/js-*.o

.PHONY: all clean
